using CatalogService.Core.ValueObjects;

namespace CatalogService.Web.ApiModels;

// ApiModel DTOs are used by ApiController classes and are typically kept in a side-by-side folder
public class CategoryDTO : CreateCategoryDTO
{
  public CategoryDTO(int id, string name, int? parentId = null, string? image = null, List<ItemDTO>? items = null) : base(name, parentId, image)
  {
    Id = id;
    Items = items ?? new List<ItemDTO>();
  }
  public int Id { get; set; }
  public List<ItemDTO> Items { get; set; }
}

// Creation DTOs should not include an ID if the ID will be generated by the back end
public abstract class CreateCategoryDTO
{
  protected CreateCategoryDTO(string name, int? parentId, string? image)
  {
    Name = name;
    ParentId = parentId;
    if (!string.IsNullOrEmpty(image))
    {
      Image = new Image(image);
    }
  }
  public string Name { get; set; }
  public int? ParentId { get; set; }
  public Image? Image { get; set; }
}
