name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies carting
      run: dotnet restore
      working-directory: CartingService
    - name: Build carting
      run: dotnet build --configuration Release CartingService.sln
      working-directory: CartingService
    - name: Test carting
      run: dotnet test --no-build --verbosity normal      
      working-directory: CartingService
      
    - name: Restore dependencies catalog
      run: dotnet restore
      working-directory: CatalogService/src
    - name: Build catalog
      run: dotnet build --configuration Release CatalogService.sln
      working-directory: CatalogService/src
    - name: Test catalog
      run: dotnet test --no-build --verbosity normal
      working-directory: CatalogService/test/CatalogService.UnitTests
