name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: CartingService
    - name: Build
      run: dotnet build --configuration Release CartingService.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
      working-directory: CatalogService
    - name: Build
      run: dotnet build --configuration Release CatalogService.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal
